### ISSUE TITLE
Undefined variable $err

### ISSUE THREAD

**Issue by fluxxus** [tbm-productions/Password-Protected-Page#2]
Hey, 

I plan to use your script on one website, but I get the undefined variable error. 

Basically on fresh load of `auth.php` I get this: `Notice: Undefined variable: err`. If I click on Enter submit button without providing working password, only then it shows error message in red - The password you entered was incorrect. 
And the `Notice: Undefined variable: err` is removed also.

How to get rid of this undefined variable? I understand what is going on, but since I am a designer who writes front-end code I am not that familiar with PHP, especially the sessions part where that `$err` is initially declared.

**Comment by fluxxus** [comment]
I solved it by declaring the variable above `if-else` block, cause it won't be available outside the block otherwise.

Just added `$err = "";` below password variable declaration.

**Comment by benmccormick04** [comment]
Hi, that is to do with your PHP Error reporting level, if you want notices to be hidden change your error reporting level like so:

```
<?php
error_reporting(E_ALL & ~E_NOTICE);
?>
```

Hope this helps!

**Comment by fluxxus** [comment]
Ok, thanks for the clarification!
